apiVersion: apps/v1
metadata: 
   name: orders-ignore
   namespace: development
   annotations:
       client.lifecycle.config.k8s.io/deletion: detach
      
   labels:
     type: ignore
kind: Deployment
spec:
   selector:
      matchLabels:
         app: orders
         
   replicas: 4
   template:
     metadata:
        labels:
           app: orders
     spec:
       containers:
       - name: orders
         image: gcr.io/gkemhcs-eswari/orders
         ports:
         - containerPort: 8080
 
